name: Deespligue a de Portafolio

on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
env:
  DEPLOY_BASE_URL: ${{vars.DEPLOY_BASE_URL}}
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy: 
    environment:
      name: github-pages
      url: ${{ steps.github_pages.outputs.url }}

    runs-on: ubuntu-latest
    steps: 
      - name: Clonar repositorio
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Instalar Dependencias
        run: npm install
      - name: Verificar variables de ambiente
        run: echo "DEPLOY_BASE_URL $DEPLOY_BASE_URL"
      - name: Compilar Proyecto
        run: npm run build
      - name: Configuracion de github
        uses: actions.cinfigure-pages@v5
      - name : Subir Compilado a Github 
        uses: actions/uploud-pages-artifact@v3
        with:
          path: './dist'
      - name: Publicar Pagina
        id: deployment
        uses: actions/deply-pages@v4